input {
	beats {
		port => 5044
	}

	tcp {
		port => 50000
	}

	udp {
		port => 50000
	}
}

## Add your filters / logstash plugins configuration here

filter {
	grok {
        	match => { "message" => "%{WORD:device_id} %{NUMBER:message_seq} %{NUMBER:uptime:float} %{NUMBER:unknown1} %{NUMBER:unknown2}\|%{NOTSPACE:function}%{SPACE}(Tick|Tock) uptime: %{NUMBER:tock_uptime:float}, RAM: %{NUMBER:ram:int}, Cur Free:%{NUMBER:cur_free:int}, Min Free:%{NUMBER:min_free:int}" }
    	}
    	grok {
        	match => { "message" => "%{WORD:device_id} %{NUMBER:message_seq} %{NUMBER:uptime:float} %{NUMBER:unknown1} %{NUMBER:unknown2}\|%{NOTSPACE:function}%{SPACE}%{GREEDYDATA:message}" }
    	}
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
#		template_name => "logs-template"
#		template => "/usr/share/logstash/templates/logstash.template.json"
	}
}
